UI/contactnsubs
SaadBJavaid/Fast-Clean-Service pull request #15
Opened 2024-10-06 17:31 UTC by hassanabbas16

**Assigned Tasks:**

**Booking form:**
1. Making the booking form steps 4 5 6 7 9 and 10 responsive as outlined in the figma for booking form responsiveness

**Screenshots:**
![screencapture-localhost-3000-booking-2024-10-06-10_23_22](https://github.com/user-attachments/assets/58213371-64f4-46ac-b8c3-71bcd2e00fcf)
![screencapture-localhost-3000-booking-2024-10-06-10_21_34](https://github.com/user-attachments/assets/b0e02a12-ec87-4192-927a-64f28c488e87)
![screencapture-localhost-3000-booking-2024-10-06-10_22_05](https://github.com/user-attachments/assets/bb045713-238f-4325-a972-08f08492bec4)
![screencapture-localhost-3000-booking-2024-10-06-10_22_21](https://github.com/user-attachments/assets/2c1f8b3a-90b7-4ac0-bf76-cc3f629e4ebc)
![screencapture-localhost-3000-booking-2024-10-06-10_22_37](https://github.com/user-attachments/assets/0f20eb18-dce7-4e0d-82b3-44251daff998)
![screencapture-localhost-3000-booking-2024-10-06-10_22_58](https://github.com/user-attachments/assets/656dd0c4-6a90-4688-a8db-7b93e9a9dc40)
![screencapture-localhost-3000-booking-2024-10-06-10_23_10](https://github.com/user-attachments/assets/b8e5432c-0bb6-4eb5-8368-61bcebef8da8)

2024-10-07 23:41 UTC, anasbinarif requested changes

2024-10-07 23:41 UTC, anasbinarif commented on src/app/subscribe/page.jsx
> +                <img src={`/bookingFormIcons/sub${index + 1}.png`} alt={`${pkg.name} image`} style={{ width: '460px', height: '270px', objectFit: 'cover', boxShadow: theme.palette.mode === 'light' ?
why are you using style here? also, try to move the style to a separate file if its more than 4 5 lines in the whole code. contact Faizan if you need any help

2024-10-07 23:41 UTC, anasbinarif commented on src/app/subscribe/page.jsx
> +                        <img src="/bookingFormIcons/Checkmark.png" alt="Checkmark" />
use Image from nextjs

2024-10-07 23:41 UTC, anasbinarif commented on src/components/BookingForm/PersonParticularsStep/BookingParticulars.jsx
> -export const FormTwoColumn = styled(Box)(({ theme }) => ({
move this to .style file, if you don't know about this text me on slack we will have aa short call

2024-10-07 23:41 UTC, anasbinarif commented on src/components/BookingForm/SubscriptionPackagesStep/SubscriptionPackages.jsx
> +              breakpoints={{
why are breakpoints defined here and not in the create theme globally?

2024-10-07 23:41 UTC, anasbinarif commented on src/components/BookingForm/SummaryStep/Summary.jsx
> -const SummaryHeading = styled(Typography)(({ theme }) => ({
move this to separate .style file

2024-10-07 23:41 UTC, anasbinarif commented on src/components/Home/ServicesOverview/ServiceOverviewPckgs.jsx
> +export const ContactCardContainer = styled(Box)(({theme}) => ({
this too

2024-10-07 23:42 UTC, anasbinarif commented
also kindly resolve deployment errors

2024-10-08 10:33 UTC, fizo-neechan commented
@hassanabbas16 For the last time man, make your PR properly with titles and descriptions that reflect what the the task was and how you have achieved it.

2024-10-08 10:35 UTC, fizo-neechan commented
And for the love of god, use a formatter like prettier or whatever and use a linter. Why am i getting these kinds of import errors [1db4512](https://github.com/SaadBJavaid/Fast-Clean-Service/pull/15/commits/1db45123cb248f57fb550336e4cf9f35dc204c0f)

2024-10-11 22:28 UTC, anasbinarif requested changes
kindly recheck the commits in this pr, it has faizan commits too

2024-10-11 22:29 UTC, anasbinarif commented
the deployment got failed

2024-10-17 17:03 UTC, merged